### ISSUE TITLE
Absolutely love it, looks so damn good, but only seems to cover 1920x wide.

### ISSUE THREAD

**Issue by eth** [OscarL/MatrixSS#2]
I have quite a few monitors and it drips down from the top left one into the one under it just a little then bounces and stops.
Unfortunately the glyphs are only on that left most monitor, haven't figured out a way to get it to envelop all my displays! Any and all help would be greatly appreciated!

**Comment by OscarL** [comment]
Hello, glad you like MatrixSS too! Louai Munajim really did a great job with this one :-)

Regarding the multimonitors... the current code uses `GetSystemMetrics()` to ask for `SM_CXSCREEN` and `SM_CYSCREEN` to get the screen size, but that only ever returns the size of the primary display monitor.

I guess a quick and dirty thing to try would be replace that by asking for `SM_CXVIRTUALSCREEN` / `SM_CYVIRTUALSCREEN` instead, as [according to MS docs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics):

    The virtual screen is the bounding rectangle of all display monitors.

And hope that's all what's needed for MatrixSS to cover all the monitors. Maybe some of the settings will need to be tweaked too, to make sure there are enough "streams" to cover the increased resolution.

Not sure I would be able to test if that works, thou (I've only one monitor).

If it requires more changes than that, I'm afraid I won't be of much help, as my skills are pretty limited.

I've currently don't have a working setup to compile a version with the mentioned changes, so it might take me a while to get back to you with a test binary. Poke me if you don't hear from me in the next week or two :-)

**Comment by OscarL** [comment]
@eth... could you try with the following test version, to see if it works better with your monitor setup?

[MatrixSS-multi-monitor.zip](https://github.com/OscarL/MatrixSS/files/10528878/MatrixSS-multi-monitor.zip)

I have tried it with an old netbook + monitor (1024x600 + 1920x1080) both with the screens setup "side by side" and with the smaller one on top of the big one.

I could reproduce your findings with the previous version (the fall-through to the lower monitor until it stops), but with this test version, it seems to work as it should! (at least on that WinXP 32 bits netbook).

I'll wait some time for your confirmation, before making a new release. Ha! Never really expected to be anything else than the v1.0 one :-D

Thanks in advance.

**Comment by OscarL** [comment]
After testing it on a Win10 64 bits laptop + external monitor (works well for me there too), I think this is as good as I can make it be.

Made a new release for [v1.1](https://github.com/OscarL/MatrixSS/releases/tag/v1.1).

Hopefully, it will work for you too @eth!
